---
- name: Add worker to manager node
  docker_swarm:
    state: join
    advertise_addr: worker
    join_token: "{{ hostvars['10.172.0.15']['swarm_info']['swarm_facts']['JoinTokens']['Worker']  }}"
    remote_addrs: ['dnd-managerz:2377']